
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author AnthonyCee
 */
public class Accountblocker extends javax.swing.JInternalFrame {
Connection con = myconnect.getConnection();
        PreparedStatement ps;
        ResultSet rs;
    /**
     * Creates new form Accountblocker
     */
    public Accountblocker() {
        initComponents();
          txtdate.setDate(java.sql.Date.valueOf(java.time.LocalDate.now()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtaccno = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtcom = new javax.swing.JTextArea();
        view = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        txtdate = new com.toedter.calendar.JDateChooser();
        txtname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtbal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("ACCOUNT BLOCKER");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/sunlog.png"))); // NOI18N

        jLabel1.setText("Account No");

        txtaccno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtaccnoKeyReleased(evt);
            }
        });

        txtcom.setColumns(20);
        txtcom.setRows(5);
        jScrollPane1.setViewportView(txtcom);

        view.setText("View Blocked Account Details");
        view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });

        jButton1.setText("UnBlock");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtname.setEnabled(false);

        jLabel2.setText("Account Name");

        txtbal.setEnabled(false);

        jLabel3.setText("Account Bal");

        jLabel4.setText("Date");

        jButton2.setText("Block");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Close");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel5.setText("Comment");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(42, 42, 42)
                .addComponent(jButton1)
                .addGap(30, 30, 30)
                .addComponent(jButton3)
                .addGap(60, 60, 60))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(view)
                                    .addComponent(txtaccno, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtname)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtdate, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtbal))
                                .addContainerGap())))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(view)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtaccno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtbal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel4))
                    .addComponent(txtdate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtaccnoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtaccnoKeyReleased
        try {
            // TODO add your handling code here:
            if (view.isSelected()){
                String qry = "SELECT * FROM `blockedaccountable` WHERE AccountNo = '"+txtaccno.getText()+"'";
                ps = con.prepareStatement(qry);
                rs = ps.executeQuery();
                while(rs.next()){

                    String add1 = rs.getString("AccountName");
                    txtname.setText(add1);
                    String add2 = rs.getString("AccountBalance");
                    txtbal.setText(add2);
                    String date = rs.getString("Date");
                    ( (JTextField)txtdate.getDateEditor().getUiComponent()).setText(date);

                    String add3 = rs.getString("Comment");
                    txtcom.setText(add3);
                }

            }else{
                String qry2 = "SELECT Name,AccountBalance FROM `customertable` WHERE AccountNo = '"+txtaccno.getText()+"'";
                try {
                    ps = con.prepareStatement(qry2);

                    rs = ps.executeQuery();
                    while(rs.next()){

                        String add1 = rs.getString("Name");
                        txtname.setText(add1);
                        String add2 = rs.getString("AccountBalance");
                        txtbal.setText(add2);

                    }
                } catch (SQLException ex) {
                    Logger.getLogger(Accountblocker.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(Accountblocker.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtaccnoKeyReleased

    private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            
        if(FRONTPAGE.copt.getSelectedItem()== "ADMIN"){
        int conf = JOptionPane.showConfirmDialog(this, "This will unblock this user account and \ngrant the user total access to his/her account \n Do you want to continue?","WARNING", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        
        if(txtaccno.getText().equals("")){
       JOptionPane.showMessageDialog(this,"Please enter the user's Account Number to continue");
       
       }else if(conf ==JOptionPane.YES_OPTION){
        
        try {
            // TODO add your handling code here:
            String Sql = "DELETE FROM `blockedaccountable` WHERE AccountNo = '"+txtaccno.getText()+"'";
            ps = con.prepareStatement(Sql);
            int del = ps.executeUpdate();

            if(del>0){
                JOptionPane.showMessageDialog(this,"Account Unblocked Successfully");

            }
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,"OOPs! An error has occurred due some mismatched information");
            Logger.getLogger(Accountblocker.class.getName()).log(Level.SEVERE, null, ex);
        }
    }else {}
        
        }else{JOptionPane.showMessageDialog(this,"This function is above your clarence level,\nplease consult the Admin for an assistance");} 
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
        if(FRONTPAGE.copt.getSelectedItem()=="ADMIN"){
        int conf = JOptionPane.showConfirmDialog(this, "This will block this user account and prevent \nthe user from any further transaction \n Do you want to continue?","WARNING", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
          if(txtaccno.getText().equals("")){
       JOptionPane.showMessageDialog(this,"Please enter the user's Account Number to continue");
          }
          else if(txtcom.getText().equals("")){
        JOptionPane.showMessageDialog(this,"Please comment on why this account blockage to continue"); 
          }else{
            
                
                try {
                    // ps.setString(1, pin.getText());
 String user = "select COUNT(*) AS total from `blockedaccountable` where AccountNo = ? ";
                ps = con.prepareStatement(user);
                ps.setString(1, txtaccno.getText());
               
                    rs = ps.executeQuery();
                    
                     while(rs.next()){

                    if(rs.getInt("total")>0){
                        JOptionPane.showMessageDialog(this,"This Account Number  already exist in \nthe blocked account list");
                    } else{
                
               
                      
                        
                        try {
                            String date = ((JTextField) txtdate.getDateEditor().getUiComponent()).getText();
                            if(conf ==JOptionPane.YES_OPTION){
                                
                                
                                // TODO add your handling code here:
                                String sql = "INSERT INTO `blockedaccountable`( `AccountNo`, `AccountName`, `AccountBalance`, `Date`, `Comment`) VALUES (?,?,?,?,?) ";
                                ps = con.prepareStatement(sql);
                                ps.setString(1, txtaccno.getText());
                                ps.setString(2, txtname.getText());
                                ps.setString(3, txtbal.getText());
                                ps.setString(4,date);
                                ps.setString(5, txtcom.getText());
                                
                                int sub = ps.executeUpdate();
                                if(sub > 0 ){
                                    
                                    JOptionPane.showMessageDialog(this, "Account Blocked Successfully");
                                }
                            }else{}
                        } catch (SQLException ex) {
                            JOptionPane.showMessageDialog(this, "Sorry an Error Occurred please confirm your details");
                            Logger.getLogger(Accountblocker.class.getName()).log(Level.SEVERE, null, ex);
                        }
                     }
                }
                  } catch (SQLException ex) {
                    Logger.getLogger(Accountblocker.class.getName()).log(Level.SEVERE, null, ex);
                }
                } 
                    
        }else{JOptionPane.showMessageDialog(this,"This function is above your clarence level,\nplease consult the Admin for an assistance");}      
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        this.hide();
        
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtaccno;
    private javax.swing.JTextField txtbal;
    private javax.swing.JTextArea txtcom;
    private com.toedter.calendar.JDateChooser txtdate;
    private javax.swing.JTextField txtname;
    private javax.swing.JCheckBox view;
    // End of variables declaration//GEN-END:variables
}
