/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author AnthonyCee
 */
public class Balsheet extends javax.swing.JInternalFrame {
Connection con = myconnect.getConnection();
     // Connection con = myconnect2.ConnectDb();
        PreparedStatement ps;
        ResultSet rs;
    /**
     * Creates new form Balsheet
     */
    public Balsheet() {
        initComponents();
        Balsheetdata();
          trandate.setDate(java.sql.Date.valueOf(java.time.LocalDate.now()));
    }
    public void Balsheetdata(){
    
      
        try {
              String q = "select * from `balancesheetable`";
            ps = con.prepareStatement(q);
             rs = ps.executeQuery();
             
           balsheettable.setModel(DbUtils.resultSetToTableModel(rs)); 
             
        } catch (SQLException ex) {
            
            Logger.getLogger(employee.class.getName()).log(Level.SEVERE, null, ex);
        }
    
     
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtbalbf = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtobal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        trandate = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        balsheettable = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        btnclose = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnsubmit = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("BALANCE SHEET");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/sunlog.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Balance B/F");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Opening Balance");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtbalbf, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtobal, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 154, Short.MAX_VALUE)
                .addComponent(trandate, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtbalbf, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtobal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(trandate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(balsheettable);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Date");

        btnclose.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnclose.setText("Close");
        btnclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncloseActionPerformed(evt);
            }
        });

        btnclear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnclear.setText("Clear");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Balance C/D");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnsubmit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnsubmit.setText("Submit");
        btnsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmitActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(230, 230, 230))
            .addGroup(layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(btnsubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnclear, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnclose, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(174, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnclear, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnclose, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 394, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitActionPerformed
        try {
            int resp = JOptionPane.showConfirmDialog(this, "Are you sure you want to Submit this? \nConfirm your entries before you go ahead.\nData submitted cannot be undone. ", "Warning",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE );
            String date = ((JTextField) trandate.getDateEditor().getUiComponent()).getText();
            String qry = "select * from  `balancesheetable` where Date = '"+date+"'";
            ps = con.prepareStatement(qry);
            rs = ps.executeQuery();

            if(!rs.next()){

                if(txtbalbf.getText().equals("")||txtobal.getText().equals("")){
                    JOptionPane.showMessageDialog(this,"Empty field(s) detected please fillin the field to proceed");

                }else{
                    try {

                        // Submiting the b/f,opening balance and the date

                        String sql = "INSERT INTO `balancesheetable`( `Balance_b_f`, `OpeningBalance`,  `TotalDeposit`, `TotalWithdrawal`, `TotalLoan`, `Date`) VALUES (?,?,?,?,?,?)";
                        ps = con.prepareStatement(sql);
                        ps.setString(1, txtbalbf.getText());
                        ps.setString(2, txtobal.getText());
                        ps.setDouble (3,0);
                        ps.setDouble (4,0);
                        ps.setDouble (5,0);
                        ps.setString(6,date);
                        if(resp == JOptionPane.YES_OPTION){
                            int k1 = ps.executeUpdate();
                            if(k1>0){

                                JOptionPane.showMessageDialog(this,"Submission was Successful");

                                Balsheetdata();
                            }
                        }else{}
                    } catch (SQLException ex) {

                        JOptionPane.showMessageDialog(this,"Submission Failed");
                        Logger.getLogger(Balsheet.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }else{
                try{

                    String sql2 = "UPDATE `balancesheetable` SET `OpeningBalance`= (`OpeningBalance` + '"+txtobal.getText()+"') where Date = '"+date+"'";
                    ps = con.prepareStatement(sql2);
                    int q = ps.executeUpdate();

                    if(q>0){

                        JOptionPane.showMessageDialog(this,"Updated was Successful");
                        Balsheetdata();
                    }

                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this,"Update failed");
                    Logger.getLogger(Balsheet.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

        } catch (SQLException ex) {
            Logger.getLogger(Balsheet.class.getName()).log(Level.SEVERE, null, ex);

        }

        //CALCULATING CASH AT HAND

        try{
            String date = ((JTextField) trandate.getDateEditor().getUiComponent()).getText();
            String sql2 = "UPDATE `balancesheetable` SET `Cash@Hand`= (`Balance_b_f` +`OpeningBalance`) where Date = '"+date+"'";
            ps = con.prepareStatement(sql2);
            int q = ps.executeUpdate();

            if(q>0){

                // JOptionPane.showMessageDialog(this,"Updated was Successful");
                Balsheetdata();
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,"Update failed");
            Logger.getLogger(Balsheet.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnsubmitActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        // TODO add your handling code here:
        txtbalbf.setText("");
        txtobal.setText("");
    }//GEN-LAST:event_btnclearActionPerformed

    private void btncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncloseActionPerformed
        // close
        this.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        this.hide();
    }//GEN-LAST:event_btncloseActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String date = ((JTextField) trandate.getDateEditor().getUiComponent()).getText();
        try {
            // TODO add your handling code here:
            //
            String qry = "select * from  `balancesheetable` where Date = '"+date+"'";
            ps = con.prepareStatement(qry);
            rs = ps.executeQuery();
            if(rs.next()){
                try{

                    String sql2 = "UPDATE `balancesheetable` SET `CreditBalance_c_d`= (`Cash@Hand` +`TotalDeposit`), `DebitBalance_b_d`= (`TotalWithdrawal`+`TotalLoan`),`ClosingBalance_c_d`= (`CreditBalance_c_d` - `DebitBalance_b_d`)    where Date = '"+date+"'";
                    ps = con.prepareStatement(sql2);
                    int q = ps.executeUpdate();

                    if(q>0){

                        JOptionPane.showMessageDialog(this,"Account Balanced Successfully");
                        Balsheetdata();
                    }

                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this," Account Balancing failed");
                    Logger.getLogger(Balsheet.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(Balsheet.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
   
        if(FRONTPAGE.copt.getSelectedItem()=="ADMIN"){
        try {
        //delete
        int confir = JOptionPane.showConfirmDialog(this, "Please confirm that the 'DATE' selected is correspond \nto the Record you want to Delete", "Warning",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
        int goahead = JOptionPane.showConfirmDialog(this, "Are you Really sure you want to Delete this Record? \n Note that this may affect your future Record Audit as this \nRecord will be Deleted from the Database Permanently.\n Click 'Ok to continue' Or 'Cancel to terminate action'","Warning",JOptionPane.YES_NO_OPTION ,JOptionPane.WARNING_MESSAGE);
        String date = ((JTextField) trandate.getDateEditor().getUiComponent()).getText();
       
         if(confir == JOptionPane.NO_OPTION || goahead == JOptionPane.NO_OPTION ){
         }else{
         
        String del = "DELETE FROM `balancesheetable` WHERE Date = '"+date+"'";
        ps = con.prepareStatement(del);
        int d = ps.executeUpdate();
        if(confir == JOptionPane.YES_OPTION && goahead == JOptionPane.YES_OPTION ){
        if(d>0){
        JOptionPane.showMessageDialog(this,"Record Deleted Successfully");
           Balsheetdata();
        }
        }
        }
    } catch (SQLException ex) {
          JOptionPane.showMessageDialog(this,"Record Deleting failed");
        Logger.getLogger(Balsheet.class.getName()).log(Level.SEVERE, null, ex);
    }
        }else{
        JOptionPane.showMessageDialog(this, "This function is beyond your clarance level consult the Admin for an assistance");
        }
      
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable balsheettable;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btnclose;
    private javax.swing.JButton btnsubmit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser trandate;
    private javax.swing.JTextField txtbalbf;
    private javax.swing.JTextField txtobal;
    // End of variables declaration//GEN-END:variables
}
