/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author AnthonyCee
 */
public class changepin extends javax.swing.JInternalFrame {
Connection con = myconnect.getConnection();
      //Connection con = myconnect2.ConnectDb();
        PreparedStatement ps;
        ResultSet rs;
    /**
    /**
     * Creates new form changepin
     */
    public changepin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        oldpass = new javax.swing.JPasswordField();
        newpass = new javax.swing.JPasswordField();
        conpass = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BTNCHANGE = new javax.swing.JButton();
        BTNCANL = new javax.swing.JButton();
        showhide = new javax.swing.JCheckBox();
        USERNAME = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Password Reset Master");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/sunlog.png"))); // NOI18N

        jLabel1.setText("OLD PASSWORD");

        jLabel2.setText("CONFIRM PASS.");

        jLabel3.setText("NEW PASSWORD");

        BTNCHANGE.setText("CHANGE");
        BTNCHANGE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCHANGEActionPerformed(evt);
            }
        });

        BTNCANL.setText("CANCEL");
        BTNCANL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCANLActionPerformed(evt);
            }
        });

        showhide.setText("Show/Hide Password");
        showhide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showhideActionPerformed(evt);
            }
        });

        jLabel4.setText("USERNAME");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BTNCHANGE, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(BTNCANL, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(showhide, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(conpass, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                    .addComponent(oldpass)
                    .addComponent(USERNAME)
                    .addComponent(newpass))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(USERNAME, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(oldpass, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(newpass, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(conpass, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showhide)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNCHANGE, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNCANL, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 422, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNCHANGEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCHANGEActionPerformed
        //check if empty field exist if true complain else execute
        if(newpass.getText().equals("")||oldpass.getText().equals("")||  conpass.getText().equals("")||USERNAME.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Empty field detected, fill up the field to proceed");

        }else{

            //check if the new passord entered is the same with the confirmation password if true execute else void and throw complain msg
            if(newpass.getText().equals(conpass.getText())){

                try {
                    // validate the password entered and change if it matches with the password in the database else void
                    String auth = "select * from customertable where PIN = ? and Username =?";

                    ps = con.prepareStatement(auth);
                    ps.setString(1, oldpass.getText());
                    ps.setString(2, USERNAME.getText());
                    rs = ps.executeQuery();
                    //when validation is true then execute update
                    if(rs.next()){
                        String sql = "update customertable set PIN = '"+newpass.getText()+"' where Username = '"+USERNAME.getText()+"'";

                        ps = con.prepareStatement(sql);

                        int ok =    ps.executeUpdate();

                        if(ok>0){
                            JOptionPane.showMessageDialog(null,"PIN has been changed successfully");

                        }

                    }

                    else{
                        JOptionPane.showMessageDialog(this,"PIN changing failed, confirm that old \npassword or Username supplied is correct");

                    }
                } catch (SQLException ex) {
                    // JOptionPane.showMessageDialog(null,"PIN changing failed, confirm that Username supplied is correct");

                    Logger.getLogger(changepin.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            else{
                JOptionPane.showMessageDialog(this,"Your PIN did not Match");
            }
        }
    }//GEN-LAST:event_BTNCHANGEActionPerformed

    private void BTNCANLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCANLActionPerformed
        // TODO add your handling code here:
        this.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        this.hide();
    }//GEN-LAST:event_BTNCANLActionPerformed

    private void showhideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showhideActionPerformed
        // reveal or hide the password

        if(showhide.isSelected()==true){

            oldpass.setEchoChar((char)0);
            newpass.setEchoChar((char)0);
            conpass.setEchoChar((char)0);

        }else{
            oldpass.setEchoChar('*');
            newpass.setEchoChar('*');
            conpass.setEchoChar('*');

        }
    }//GEN-LAST:event_showhideActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNCANL;
    private javax.swing.JButton BTNCHANGE;
    private javax.swing.JTextField USERNAME;
    private javax.swing.JPasswordField conpass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField newpass;
    private javax.swing.JPasswordField oldpass;
    private javax.swing.JCheckBox showhide;
    // End of variables declaration//GEN-END:variables
}
