/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author AnthonyCee
 */
public class chequereq extends javax.swing.JInternalFrame {
Connection con = myconnect.getConnection();
     // Connection con = myconnect2.ConnectDb();
        PreparedStatement ps;
        ResultSet rs;

    /**
     * Creates new form chequereq
     */
    public chequereq() {
        initComponents();
        populatecombobranch();
        //txtserial.setVisible(false);
        // cheque2.setSelected(true);
    }
 public void populatecombobranch(){
    try {
        String sql = "select * from`branchtable`";
        ps = con.prepareStatement(sql);
        rs = ps.executeQuery();
        while(rs.next()){
       RepBran.addItem(rs.getString("Branch"));
        
        }
    } catch (SQLException ex) {
        Logger.getLogger(accountype.class.getName()).log(Level.SEVERE, null, ex);
    }
    
    
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        cheque1 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        cheque2 = new javax.swing.JCheckBox();
        txtaccname = new javax.swing.JTextField();
        txtaccno = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtacctype = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        RepBran = new javax.swing.JComboBox<>();
        txtserial = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        jButton3.setText("Cancel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        setClosable(true);
        setIconifiable(true);
        setTitle("CHEQUE REQUEST");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/sunlog.png"))); // NOI18N

        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Request");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(cheque1);
        cheque1.setText("New Cheque User");
        cheque1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cheque1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Account  Name");

        buttonGroup1.add(cheque2);
        cheque2.setText(" Replace Finished Cheque");
        cheque2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cheque2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Account NO");

        jLabel3.setText("Account Type");

        jLabel4.setText("Reception Branch");

        RepBran.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Branch", "OJO Alaba", "Ojo Festac", "Ojo Igando" }));
        RepBran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RepBranActionPerformed(evt);
            }
        });

        jLabel5.setText("Serial No of the Finished Cheque ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cheque1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cheque2)
                                        .addGap(0, 41, Short.MAX_VALUE))
                                    .addComponent(RepBran, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addComponent(txtaccname))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(txtaccno))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(28, 28, 28)
                                .addComponent(txtacctype))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtserial)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(47, 47, 47)
                        .addComponent(jButton1)
                        .addGap(128, 128, 128))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtaccname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtaccno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtacctype, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(RepBran, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cheque1)
                    .addComponent(cheque2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtserial, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        this.hide();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String treq = null;
        if (cheque1.isSelected()==true){
            treq = "New Cheque User";
        }
        else if(cheque2.isSelected()==true){

            treq = "Replace Finished Cheque";

        }

        int resp = JOptionPane.showConfirmDialog(null, "Are you Sure you want to Submit this request?", "Warning", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if( txtaccname.getText().equals("")||txtaccno.getText().equals("")||txtacctype.getText().equals("")) {

            JOptionPane.showMessageDialog(this, "Empty field has been detected please fill in to progress");
        }else{

            try {
                // TODO add your handling code here:

                String qry = "INSERT INTO `requesitiontable`( `AccountName`, `AccountNo`, `AccountType`, `ReceptionBranch`, `TypeofRequest`, `SerialNo`) VALUES (?,?,?,?,?,?)";
                ps = con.prepareStatement(qry);
                ps.setString(1, txtaccname.getText());
                ps.setString(2, txtaccno.getText());
                ps.setString(3, txtacctype.getText());
                ps.setString(4, RepBran.getSelectedItem().toString());
                ps.setString(5, treq);
                ps.setString(6, txtserial.getText());
                if(resp == JOptionPane.YES_OPTION){
                    int ex =      ps.executeUpdate();

                    if (ex > 0){

                        JOptionPane.showMessageDialog(null,"Request Submitted Successfully");
                    }
                }else{}
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,"Request Submission failed");
                Logger.getLogger(chequereq.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        this.hide();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cheque2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cheque2ActionPerformed
        // TODO add your handling code here:
        
        if(cheque2.isSelected()== true){
            txtserial.setVisible(true);
        }

    }//GEN-LAST:event_cheque2ActionPerformed

    private void RepBranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RepBranActionPerformed
        // TODO add your handling code here:
       
     
    }//GEN-LAST:event_RepBranActionPerformed

    private void cheque1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cheque1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cheque1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> RepBran;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cheque1;
    private javax.swing.JCheckBox cheque2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtaccname;
    private javax.swing.JTextField txtaccno;
    private javax.swing.JTextField txtacctype;
    private javax.swing.JTextField txtserial;
    // End of variables declaration//GEN-END:variables
}
