/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.Image;
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author AnthonyCee
 */
public class profile extends javax.swing.JInternalFrame {
Connection con = myconnect.getConnection();
      //Connection con = myconnect2.ConnectDb();
     // Connection con = myconnect2.ConnectDb();
        PreparedStatement ps;
        ResultSet rs;
    /**
     * Creates new form profile
     */
    public profile() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtsearch = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        display = new javax.swing.JTextArea();
        SearchKey = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        passp = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        signature = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtsearch1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        display1 = new javax.swing.JTextArea();
        SearchKey1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        passp1 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        signature1 = new javax.swing.JLabel();

        txtsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsearchActionPerformed(evt);
            }
        });
        txtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsearchKeyReleased(evt);
            }
        });

        jButton1.setText("View ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Search Key");

        display.setEditable(false);
        display.setColumns(20);
        display.setRows(5);
        jScrollPane1.setViewportView(display);

        SearchKey.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select SearchKey", "Account No", "Email ID", "Mobil No","Name" }));

        jLabel3.setText("Search By");

        passp.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 204, 204)));

        jButton3.setText("Cancel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Print");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        signature.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 204, 204)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtsearch))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(SearchKey, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signature, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SearchKey, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(signature, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(passp, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE))
        );

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("CUSTOMER'S PROFILE");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/sunlog.png"))); // NOI18N

        txtsearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsearch1ActionPerformed(evt);
            }
        });
        txtsearch1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsearch1KeyReleased(evt);
            }
        });

        jButton2.setText("View ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Search Key");

        display1.setEditable(false);
        display1.setColumns(20);
        display1.setRows(5);
        jScrollPane2.setViewportView(display1);

        SearchKey1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select SearchKey", "Account No", "Email ID", "Mobil No","Name" }));
        SearchKey1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchKey1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Search By");

        passp1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 204, 204)));

        jButton6.setText("Cancel");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Clear");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Print");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        signature1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 204, 204)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtsearch1))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(SearchKey1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passp1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signature1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SearchKey1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtsearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(signature1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(passp1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsearchActionPerformed

    private void txtsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchKeyReleased
        
    }//GEN-LAST:event_txtsearchKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //searching by btnclick
        String searchKey = SearchKey.getSelectedItem().toString();
        switch(searchKey){

            case "Account No":

            try {
                String q = "select * from customertable where AccountNo = '"+txtsearch.getText()+"'";
                ps = con.prepareStatement(q);
                rs = ps.executeQuery();

                if(rs.next()){
                    //this will append of display the values of the text box
                    //this will append of display the values of the text box

                    byte[] img = null;
                    img =  rs.getBytes("Passport");
                    ImageIcon image = new ImageIcon(img);
                    Image im = image.getImage();
                    Image myImg = im.getScaledInstance(   passp.getWidth(),   passp.getHeight(),Image.SCALE_SMOOTH);
                    ImageIcon newImage = new ImageIcon(myImg);

                    passp.setIcon(newImage);

                    //================================================================
                    byte[] imge = null;

                    imge =  rs.getBytes("Signature");
                    ImageIcon imag = new ImageIcon(imge);
                    Image imm = imag.getImage();
                    Image myImg2 = imm.getScaledInstance(   signature.getWidth(),   signature.getHeight(),Image.SCALE_SMOOTH);
                    ImageIcon newImage2 = new ImageIcon(myImg2);

                    signature.setIcon(newImage2);

                    display1.append("\t\nAKU' UMUNNE MICROFINANCE BANK:\n" +
                        "\n======================================================\n\n" +
                        "Customer ID :\t\t\t\t " + rs.getString("CustomerID") +
                        "\n\nAccount No:\t\t\t\t " + rs.getString("AccountNO")+
                        "\n\nAccount Name:\t\t\t\t " +  rs.getString("Name") +
                        "\n\nUsername :\t\t\t\t " + rs.getString("Username") +
                        "\n\nSex:\t\t\t\t " +rs.getString("Sex")  +
                        "\n\nDate of Birth:\t\t\t\t " +rs.getString("DOB") +
                        "\n\nEmail ID :\t\t\t\t " + rs.getString("EmailID") +
                        "\n\nPhone No:\t\t\t\t" + rs.getString("MobileNo") +
                        "\n\nAddress:\t\t\t\t " + rs.getString("Address") +
                        "\n\nCustomerActiveness:\t\t\t" + rs.getString("CustomerActiveness") +
                        "\n\nAccount Type:\t\t\t\t " + rs.getString("AccountType") +
                        "\n\nBranch :\t\t\t\t" + rs.getString("Branch") +
                        "\n\nAccountBalance:\t\t\t $" + rs.getString("AccountBalance") +
                        "\n======================================================\n" +
                        "\nAKU' UMUNNE MICROFINANCE BANK TEAM ");

                }

            } catch (SQLException ex) {

                Logger.getLogger(employee.class.getName()).log(Level.SEVERE, null, ex);
            }
            break;
            case "Mobil No":
            try {
                String q = "select * from customertable where MobileNo = '"+txtsearch.getText()+"'";
                ps = con.prepareStatement(q);
                rs = ps.executeQuery();

                if(rs.next()){
                    //this will append of display the values of the text box
                    byte[] img = null;
                    img =  rs.getBytes("Passport");
                    ImageIcon image = new ImageIcon(img);
                    Image im = image.getImage();
                    Image myImg = im.getScaledInstance(   passp.getWidth(),   passp.getHeight(),Image.SCALE_SMOOTH);
                    ImageIcon newImage = new ImageIcon(myImg);

                    passp.setIcon(newImage);
                    //====================================================
                    byte[] imge = null;

                    imge =  rs.getBytes("Signature");
                    ImageIcon imag = new ImageIcon(imge);
                    Image imm = imag.getImage();
                    Image myImg2 = imm.getScaledInstance(   signature.getWidth(),   signature.getHeight(),Image.SCALE_SMOOTH);
                    ImageIcon newImage2 = new ImageIcon(myImg2);

                    signature.setIcon(newImage2);

                   display1.append("\t\nAKU' UMUNNE MICROFINANCE BANK:\n" +
                        "\n======================================================\n\n" +
                        "Customer ID :\t\t\t\t " + rs.getString("CustomerID") +
                        "\n\nAccount No:\t\t\t\t " + rs.getString("AccountNO")+
                        "\n\nAccount Name:\t\t\t\t " +  rs.getString("Name") +
                        "\n\nUsername :\t\t\t\t " + rs.getString("Username") +
                        "\n\nSex:\t\t\t\t " +rs.getString("Sex")  +
                        "\n\nDate of Birth:\t\t\t\t " +rs.getString("DOB") +
                        "\n\nEmail ID :\t\t\t\t " + rs.getString("EmailID") +
                        "\n\nPhone No:\t\t\t\t" + rs.getString("MobileNo") +
                        "\n\nAddress:\t\t\t\t " + rs.getString("Address") +
                        "\n\nCustomerActiveness:\t\t\t" + rs.getString("CustomerActiveness") +
                        "\n\nAccount Type:\t\t\t\t " + rs.getString("AccountType") +
                        "\n\nBranch :\t\t\t\t" + rs.getString("Branch") +
                        "\n\nAccountBalance:\t\t\t $" + rs.getString("AccountBalance") +
                        "\n======================================================\n" +
                        "\nAKU' UMUNNE MICROFINANCE BANK TEAM ");

                }

            } catch (SQLException ex) {

                Logger.getLogger(employee.class.getName()).log(Level.SEVERE, null, ex);
            }
            break;

            case "Email ID" :

            try {
                String q = "select * from customertable where EmailID = '"+txtsearch.getText()+"'";
                ps = con.prepareStatement(q);
                rs = ps.executeQuery();

                if(rs.next()){
                    byte[] img = null;
                    img =  rs.getBytes("Passport");
                    ImageIcon image = new ImageIcon(img);
                    Image im = image.getImage();
                    Image myImg = im.getScaledInstance(   passp.getWidth(),   passp.getHeight(),Image.SCALE_SMOOTH);
                    ImageIcon newImage = new ImageIcon(myImg);

                    passp.setIcon(newImage);
                    //-------------------------------------------------------
                    byte[] imge = null;

                    imge =  rs.getBytes("Signature");
                    ImageIcon imag = new ImageIcon(imge);
                    Image imm = imag.getImage();
                    Image myImg2 = imm.getScaledInstance(   signature.getWidth(),   signature.getHeight(),Image.SCALE_SMOOTH);
                    ImageIcon newImage2 = new ImageIcon(myImg2);

                    signature.setIcon(newImage2);

                    //this will append of display the values of the text box
                    //this will append of display the values of the text box
                    display1.append("\t\nAKU' UMUNNE MICROFINANCE BANK:\n" +
                        "\n======================================================\n\n" +
                        "Customer ID :\t\t\t\t " + rs.getString("CustomerID") +
                        "\n\nAccount No:\t\t\t\t " + rs.getString("AccountNO")+
                        "\n\nAccount Name:\t\t\t\t " +  rs.getString("Name") +
                        "\n\nUsername :\t\t\t\t " + rs.getString("Username") +
                        "\n\nSex:\t\t\t\t " +rs.getString("Sex")  +
                        "\n\nDate of Birth:\t\t\t\t " +rs.getString("DOB") +
                        "\n\nEmail ID :\t\t\t\t " + rs.getString("EmailID") +
                        "\n\nPhone No:\t\t\t\t" + rs.getString("MobileNo") +
                        "\n\nAddress:\t\t\t\t " + rs.getString("Address") +
                        "\n\nCustomerActiveness:\t\t\t" + rs.getString("CustomerActiveness") +
                        "\n\nAccount Type:\t\t\t\t " + rs.getString("AccountType") +
                        "\n\nBranch :\t\t\t\t" + rs.getString("Branch") +
                        "\n\nAccountBalance:\t\t\t $" + rs.getString("AccountBalance") +
                        "\n======================================================\n" +
                        "\nAKU' UMUNNE MICROFINANCE BANK TEAM ");
                }

            } catch (SQLException ex) {

                Logger.getLogger(employee.class.getName()).log(Level.SEVERE, null, ex);
            }

            break;

            case "Name":

            try {
                String q = "select * from customertable where Name = '"+txtsearch.getText()+"'";
                ps = con.prepareStatement(q);
                rs = ps.executeQuery();

                if(rs.next()){
                    byte[] img = null;
                    img =  rs.getBytes("Passport");
                    ImageIcon image = new ImageIcon(img);
                    Image im = image.getImage();
                    Image myImg = im.getScaledInstance(   passp.getWidth(),   passp.getHeight(),Image.SCALE_SMOOTH);
                    ImageIcon newImage = new ImageIcon(myImg);

                    passp.setIcon(newImage);

                    byte[] imge = null;

                    imge =  rs.getBytes("Signature");
                    ImageIcon imag = new ImageIcon(imge);
                    Image imm = imag.getImage();
                    Image myImg2 = imm.getScaledInstance(   signature.getWidth(),   signature.getHeight(),Image.SCALE_SMOOTH);
                    ImageIcon newImage2 = new ImageIcon(myImg2);

                    signature.setIcon(newImage2);

                    //this will append of display the values of the text box
                    //this will append of display the values of the text box
                    display1.append("\t\nAKU' UMUNNE MICROFINANCE BANK:\n" +
                        "\n======================================================\n\n" +
                        "Customer ID :\t\t\t\t " + rs.getString("CustomerID") +
                        "\n\nAccount No:\t\t\t\t " + rs.getString("AccountNO")+
                        "\n\nAccount Name:\t\t\t\t " +  rs.getString("Name") +
                        "\n\nUsername :\t\t\t\t " + rs.getString("Username") +
                        "\n\nSex:\t\t\t\t " +rs.getString("Sex")  +
                        "\n\nDate of Birth:\t\t\t\t " +rs.getString("DOB") +
                        "\n\nEmail ID :\t\t\t\t " + rs.getString("EmailID") +
                        "\n\nPhone No:\t\t\t\t" + rs.getString("MobileNo") +
                        "\n\nAddress:\t\t\t\t " + rs.getString("Address") +
                        "\n\nCustomerActiveness:\t\t\t" + rs.getString("CustomerActiveness") +
                        "\n\nAccount Type:\t\t\t\t " + rs.getString("AccountType") +
                        "\n\nBranch :\t\t\t\t" + rs.getString("Branch") +
                        "\n\nAccountBalance:\t\t\t $" + rs.getString("AccountBalance") +
                        "\n======================================================\n" +
                        "\nAKU' UMUNNE MICROFINANCE BANK TEAM ");

                }

            } catch (SQLException ex) {

                Logger.getLogger(employee.class.getName()).log(Level.SEVERE, null, ex);
            }
            break;
            default:
            JOptionPane.showMessageDialog(this, "Select Search Key from the Combobox Above");
            break;
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        this.hide();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        display.setText("");
        txtsearch .setText("");
        passp.setIcon(null);

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            // TODO add your handling code here:
            display.print();
        } catch (PrinterException ex) {
            Logger.getLogger(profile.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txtsearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsearch1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsearch1ActionPerformed

    private void txtsearch1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearch1KeyReleased
        //searching by btnclick
        String searchKey1 = SearchKey1.getSelectedItem().toString();
        switch(searchKey1){

            case "Account No":

            try {
                String q = "select * from customertable where AccountNo = '"+txtsearch1.getText()+"'";
                ps = con.prepareStatement(q);
                rs = ps.executeQuery();

                if(rs.next()){
                    //this will append of display the values of the text box
                    //this will append of display the values of the text box
                    byte[] img = null;
                    img =  rs.getBytes("Passport");
                    ImageIcon image = new ImageIcon(img);
                    Image im = image.getImage();
                    Image myImg = im.getScaledInstance(   passp1.getWidth(),   passp1.getHeight(),Image.SCALE_SMOOTH);
                    ImageIcon newImage = new ImageIcon(myImg);

                    passp1.setIcon(newImage);
                    //------------------------------------------------------------------------
                    byte[] imge = null;

                    imge =  rs.getBytes("Signature");
                    ImageIcon imag = new ImageIcon(imge);
                    Image imm = imag.getImage();
                    Image myImg2 = imm.getScaledInstance(   signature1.getWidth(),   signature1.getHeight(),Image.SCALE_SMOOTH);
                    ImageIcon newImage2 = new ImageIcon(myImg2);

                    signature1.setIcon(newImage2);

                     display1.append("\t\nAKU' UMUNNE MICROFINANCE BANK:\n" +
                        "\n======================================================\n\n" +
                        "Customer ID :\t\t\t\t " + rs.getString("CustomerID") +
                        "\n\nAccount No:\t\t\t\t " + rs.getString("AccountNO")+
                        "\n\nAccount Name:\t\t\t\t " +  rs.getString("Name") +
                        "\n\nUsername :\t\t\t\t " + rs.getString("Username") +
                        "\n\nSex:\t\t\t\t " +rs.getString("Sex")  +
                        "\n\nDate of Birth:\t\t\t\t " +rs.getString("DOB") +
                        "\n\nEmail ID :\t\t\t\t " + rs.getString("EmailID") +
                        "\n\nPhone No:\t\t\t\t" + rs.getString("MobileNo") +
                        "\n\nAddress:\t\t\t\t " + rs.getString("Address") +
                        "\n\nCustomerActiveness:\t\t\t" + rs.getString("CustomerActiveness") +
                        "\n\nAccount Type:\t\t\t\t " + rs.getString("AccountType") +
                        "\n\nBranch :\t\t\t\t" + rs.getString("Branch") +
                        "\n\nAccountBalance:\t\t\t $" + rs.getString("AccountBalance") +
                        "\n======================================================\n" +
                        "\nAKU' UMUNNE MICROFINANCE BANK TEAM ");

                }

            } catch (SQLException ex) {

                Logger.getLogger(employee.class.getName()).log(Level.SEVERE, null, ex);
            }
            break;
            case "Mobil No":
            try {
                String q = "select * from customertable where MobileNo = '"+txtsearch1.getText()+"'";
                ps = con.prepareStatement(q);
                rs = ps.executeQuery();

                if(rs.next()){
                    //this will append of display the values of the text box
                    //this will append of display the values of the text box
                    byte[] img = null;
                    img =  rs.getBytes("Passport");
                    ImageIcon image = new ImageIcon(img);
                    Image im = image.getImage();
                    Image myImg = im.getScaledInstance(   passp1.getWidth(),   passp1.getHeight(),Image.SCALE_SMOOTH);
                    ImageIcon newImage = new ImageIcon(myImg);

                    passp1.setIcon(newImage);

                    //==================================================================
                    byte[] imge = null;

                    imge =  rs.getBytes("Signature");
                    ImageIcon imag = new ImageIcon(imge);
                    Image imm = imag.getImage();
                    Image myImg2 = imm.getScaledInstance(   signature1.getWidth(),   signature1.getHeight(),Image.SCALE_SMOOTH);
                    ImageIcon newImage2 = new ImageIcon(myImg2);

                    signature1.setIcon(newImage2);

                     display1.append("\t\nAKU' UMUNNE MICROFINANCE BANK:\n" +
                        "\n======================================================\n\n" +
                        "Customer ID :\t\t\t\t " + rs.getString("CustomerID") +
                        "\n\nAccount No:\t\t\t\t " + rs.getString("AccountNO")+
                        "\n\nAccount Name:\t\t\t\t " +  rs.getString("Name") +
                        "\n\nUsername :\t\t\t\t " + rs.getString("Username") +
                        "\n\nSex:\t\t\t\t " +rs.getString("Sex")  +
                        "\n\nDate of Birth:\t\t\t\t " +rs.getString("DOB") +
                        "\n\nEmail ID :\t\t\t\t " + rs.getString("EmailID") +
                        "\n\nPhone No:\t\t\t\t" + rs.getString("MobileNo") +
                        "\n\nAddress:\t\t\t\t " + rs.getString("Address") +
                        "\n\nCustomerActiveness:\t\t\t" + rs.getString("CustomerActiveness") +
                        "\n\nAccount Type:\t\t\t\t " + rs.getString("AccountType") +
                        "\n\nBranch :\t\t\t\t" + rs.getString("Branch") +
                        "\n\nAccountBalance:\t\t\t $" + rs.getString("AccountBalance") +
                        "\n======================================================\n" +
                        "\nAKU' UMUNNE MICROFINANCE BANK TEAM ");
                }

            } catch (SQLException ex) {

                Logger.getLogger(employee.class.getName()).log(Level.SEVERE, null, ex);
            }
            break;

            case "Email ID" :

            try {
                String q = "select * from customertable where EmailID = '"+txtsearch1.getText()+"'";
                ps = con.prepareStatement(q);
                rs = ps.executeQuery();

                if(rs.next()){
                    //this will append of display the values of the text box
                    //this will append of display the values of the text box

                    byte[] img = null;
                    img =  rs.getBytes("Passport");
                    ImageIcon image = new ImageIcon(img);
                    Image im = image.getImage();
                    Image myImg = im.getScaledInstance(   passp1.getWidth(),   passp1.getHeight(),Image.SCALE_SMOOTH);
                    ImageIcon newImage = new ImageIcon(myImg);

                    passp1.setIcon(newImage);
                    //============================================================
                    byte[] imge = null;

                    imge =  rs.getBytes("Signature");
                    ImageIcon imag = new ImageIcon(imge);
                    Image imm = imag.getImage();
                    Image myImg2 = imm.getScaledInstance(   signature1.getWidth(),   signature1.getHeight(),Image.SCALE_SMOOTH);
                    ImageIcon newImage2 = new ImageIcon(myImg2);

                    signature1.setIcon(newImage2);

                     display1.append("\t\nAKU' UMUNNE MICROFINANCE BANK:\n" +
                        "\n======================================================\n\n" +
                        "Customer ID :\t\t\t\t " + rs.getString("CustomerID") +
                        "\n\nAccount No:\t\t\t\t " + rs.getString("AccountNO")+
                        "\n\nAccount Name:\t\t\t\t " +  rs.getString("Name") +
                        "\n\nUsername :\t\t\t\t " + rs.getString("Username") +
                        "\n\nSex:\t\t\t\t " +rs.getString("Sex")  +
                        "\n\nDate of Birth:\t\t\t\t " +rs.getString("DOB") +
                        "\n\nEmail ID :\t\t\t\t " + rs.getString("EmailID") +
                        "\n\nPhone No:\t\t\t\t" + rs.getString("MobileNo") +
                        "\n\nAddress:\t\t\t\t " + rs.getString("Address") +
                        "\n\nCustomerActiveness:\t\t\t" + rs.getString("CustomerActiveness") +
                        "\n\nAccount Type:\t\t\t\t " + rs.getString("AccountType") +
                        "\n\nBranch :\t\t\t\t" + rs.getString("Branch") +
                        "\n\nAccountBalance:\t\t\t $" + rs.getString("AccountBalance") +
                        "\n======================================================\n" +
                        "\nAKU' UMUNNE MICROFINANCE BANK TEAM ");

                }

            } catch (SQLException ex) {

                Logger.getLogger(employee.class.getName()).log(Level.SEVERE, null, ex);
            }

            break;

            case "Name":

            try {
                String q = "select * from customertable where Name = '"+txtsearch1.getText()+"'";
                ps = con.prepareStatement(q);
                rs = ps.executeQuery();

                if(rs.next()){
                    //this will append of display the values of the text box
                    //this will append of display the values of the text box
                    byte[] img = null;
                    img =  rs.getBytes("Passport");
                    ImageIcon image = new ImageIcon(img);
                    Image im = image.getImage();
                    Image myImg = im.getScaledInstance(   passp1.getWidth(),   passp1.getHeight(),Image.SCALE_SMOOTH);
                    ImageIcon newImage = new ImageIcon(myImg);

                    passp1.setIcon(newImage);

                    //============================================================
                    byte[] imge = null;

                    imge =  rs.getBytes("Signature");
                    ImageIcon imag = new ImageIcon(imge);
                    Image imm = imag.getImage();
                    Image myImg2 = imm.getScaledInstance(   signature1.getWidth(),   signature1.getHeight(),Image.SCALE_SMOOTH);
                    ImageIcon newImage2 = new ImageIcon(myImg2);

                    signature1.setIcon(newImage2);

                    display1.append("\t\nAKU' UMUNNE MICROFINANCE BANK:\n" +
                        "\n======================================================\n\n" +
                        "Customer ID :\t\t\t\t " + rs.getString("CustomerID") +
                        "\n\nAccount No:\t\t\t\t " + rs.getString("AccountNO")+
                        "\n\nAccount Name:\t\t\t\t " +  rs.getString("Name") +
                        "\n\nUsername :\t\t\t\t " + rs.getString("Username") +
                        "\n\nSex:\t\t\t\t " +rs.getString("Sex")  +
                        "\n\nDate of Birth:\t\t\t\t " +rs.getString("DOB") +
                        "\n\nEmail ID :\t\t\t\t " + rs.getString("EmailID") +
                        "\n\nPhone No:\t\t\t\t" + rs.getString("MobileNo") +
                        "\n\nAddress:\t\t\t\t " + rs.getString("Address") +
                        "\n\nCustomerActiveness:\t\t\t" + rs.getString("CustomerActiveness") +
                        "\n\nAccount Type:\t\t\t\t " + rs.getString("AccountType") +
                        "\n\nBranch :\t\t\t\t" + rs.getString("Branch") +
                        "\n\nAccountBalance:\t\t\t $" + rs.getString("AccountBalance") +
                        "\n======================================================\n" +
                        "\nAKU' UMUNNE MICROFINANCE BANK TEAM ");

                }

            } catch (SQLException ex) {

                Logger.getLogger(employee.class.getName()).log(Level.SEVERE, null, ex);
            }
            break;
            default:
            JOptionPane.showMessageDialog(this, "Select Search Key from the Combobox Above");
            break;
        }

    }//GEN-LAST:event_txtsearch1KeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        this.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        this.hide();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        display.setText("");
        txtsearch .setText("");
        passp.setIcon(null);

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        try {
            // TODO add your handling code here:
            display.print();
        } catch (PrinterException ex) {
            Logger.getLogger(profile.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void SearchKey1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchKey1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchKey1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> SearchKey;
    private javax.swing.JComboBox<String> SearchKey1;
    private javax.swing.JTextArea display;
    private javax.swing.JTextArea display1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel passp;
    private javax.swing.JLabel passp1;
    private javax.swing.JLabel signature;
    private javax.swing.JLabel signature1;
    private javax.swing.JTextField txtsearch;
    private javax.swing.JTextField txtsearch1;
    // End of variables declaration//GEN-END:variables
}
