/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author AnthonyCee
 */
public class searchcustomer extends javax.swing.JInternalFrame {
Connection con = myconnect.getConnection();
      //Connection con = myconnect2.ConnectDb();
        PreparedStatement ps;
        ResultSet rs;
    /**
     * Creates new form searchcustomer
     */
    public searchcustomer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnsearch = new javax.swing.JButton();
        txtsearch = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblSearchcust = new javax.swing.JTable();
        SearchKey = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("SEARCH CUSTOMER");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/sunlog.png"))); // NOI18N

        btnsearch.setText("Find");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });

        txtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsearchKeyReleased(evt);
            }
        });

        jLabel1.setText("Search Record");

        jLabel2.setText("Enter AccountNo or Email or Mobile No or Name To Search");

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        TblSearchcust.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(TblSearchcust);

        SearchKey.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select SearchKey", "Account No", "Email ID", "Mobil No","Name" }));

        jLabel3.setText("Search By");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(SearchKey, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txtsearch))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnsearch)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchKey, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        // TODO add your handling code here:
        //searching by btnclick
        String searchKey = SearchKey.getSelectedItem().toString();
        switch(searchKey){

            case "Account No":

            try {
                String q = "select CustomerID,AccountNO,Name,MobileNo,Branch,AccountBalance from customertable where AccountNo = '"+txtsearch.getText()+"'";
                ps = con.prepareStatement(q);
                rs = ps.executeQuery();

                TblSearchcust.setModel(DbUtils.resultSetToTableModel(rs));

            } catch (SQLException ex) {

                Logger.getLogger(employee.class.getName()).log(Level.SEVERE, null, ex);
            }
            break;
            case "Mobile No":
            try {
                String q = "select CustomerID,AccountNO,Name,MobileNo,Branch,AccountBalance from customertable where MobileNo = '"+txtsearch.getText()+"'";
                ps = con.prepareStatement(q);
                rs = ps.executeQuery();

                TblSearchcust.setModel(DbUtils.resultSetToTableModel(rs));

            } catch (SQLException ex) {

                Logger.getLogger(employee.class.getName()).log(Level.SEVERE, null, ex);
            }
            break;

            case "Email ID" :

            try {
                String q = "select CustomerID,AccountNO,Name,MobileNo,Branch,AccountBalance from customertable where EmailID = '"+txtsearch.getText()+"'";
                ps = con.prepareStatement(q);
                rs = ps.executeQuery();

                TblSearchcust.setModel(DbUtils.resultSetToTableModel(rs));

            } catch (SQLException ex) {

                Logger.getLogger(employee.class.getName()).log(Level.SEVERE, null, ex);
            }

            break;

            case "Name":

            try {
                String q = "select CustomerID,AccountNO,Name,MobileNo,Branch,AccountBalance from customertable where Name = '"+txtsearch.getText()+"'";
                ps = con.prepareStatement(q);
                rs = ps.executeQuery();

                TblSearchcust.setModel(DbUtils.resultSetToTableModel(rs));

            } catch (SQLException ex) {

                Logger.getLogger(employee.class.getName()).log(Level.SEVERE, null, ex);
            }

            default:
            JOptionPane.showMessageDialog(this, "Select Search Key from the Combobox Above");
            break;
        }

    }//GEN-LAST:event_btnsearchActionPerformed

    private void txtsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchKeyReleased
        // search customer at keyrelease
        //searching by accountno
        String searchKey = SearchKey.getSelectedItem().toString();
        switch(searchKey){

            case "Account No":

            try {
                String q = "select CustomerID,AccountNO,Name,MobileNo,Branch,AccountBalance from customertable where AccountNo = '"+txtsearch.getText()+"'";
                ps = con.prepareStatement(q);
                rs = ps.executeQuery();

                TblSearchcust.setModel(DbUtils.resultSetToTableModel(rs));

            } catch (SQLException ex) {

                Logger.getLogger(employee.class.getName()).log(Level.SEVERE, null, ex);
            }
            break;
            case "Mobile No":
            try {
                String q = "select CustomerID,AccountNO,Name,MobileNo,Branch,AccountBalance from customertable where MobileNo = '"+txtsearch.getText()+"'";
                ps = con.prepareStatement(q);
                rs = ps.executeQuery();

                TblSearchcust.setModel(DbUtils.resultSetToTableModel(rs));

            } catch (SQLException ex) {

                Logger.getLogger(employee.class.getName()).log(Level.SEVERE, null, ex);
            }
            break;

            case "Email ID" :

            try {
                String q = "select CustomerID,AccountNO,Name,MobileNo,Branch,AccountBalance from customertable where EmailID = '"+txtsearch.getText()+"'";
                ps = con.prepareStatement(q);
                rs = ps.executeQuery();

                TblSearchcust.setModel(DbUtils.resultSetToTableModel(rs));

            } catch (SQLException ex) {

                Logger.getLogger(employee.class.getName()).log(Level.SEVERE, null, ex);
            }

            break;

            case "Name":

            try {
                String q = "select CustomerID,AccountNO,Name,MobileNo,Branch,AccountBalance from customertable where Name = '"+txtsearch.getText()+"'";
                ps = con.prepareStatement(q);
                rs = ps.executeQuery();

                TblSearchcust.setModel(DbUtils.resultSetToTableModel(rs));

            } catch (SQLException ex) {

                Logger.getLogger(employee.class.getName()).log(Level.SEVERE, null, ex);
            }
            break;
            default:
            JOptionPane.showMessageDialog(this, "Select Search Key from the Combobox Above");
            break;
        }

    }//GEN-LAST:event_txtsearchKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        this.hide();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> SearchKey;
    private javax.swing.JTable TblSearchcust;
    private javax.swing.JButton btnsearch;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtsearch;
    // End of variables declaration//GEN-END:variables
}
